### ISSUE TITLE
hs_compile_multi with a Illegal instruction error

### ISSUE THREAD

**Issue by SQBLXHQ** [intel/hyperscan#188]
hi，
  I have a problem when run in hs_compile_multi.
  This is my cpu info: Intel(R) Xeon(R) CPU  E5620  @ 2.40GHz.
  This is GDB stack information:

    Program received signal SIGILL, Illegal instruction.
0x000000000069049c in ue2::shortcutLiteral(ue2::NG&, ue2::ParsedExpression const&) ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-26.el7.x86_64 libcom_err-1.42.9-9.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libpcap-1.5.3-11.el7.x86_64 libselinux-2.5-6.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 mariadb-libs-5.5.52-1.el7.x86_64 openssl-libs-1.0.1e-60.el7.x86_64 pcre-8.42-4.el8.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x000000000069049c in ue2::shortcutLiteral(ue2::NG&, ue2::ParsedExpression const&) ()
#1  0x000000000059929b in ue2::addExpression(ue2::NG&, unsigned int, char const*, unsigned int, hs_expr_ext const*, unsigned int) ()
#2  0x0000000000597025 in ue2::hs_compile_multi_int(char const* const*, unsigned int const*, unsigned int const*, hs_expr_ext const* const*, unsigned int, unsigned int, hs_platform_info const*, hs_database**, hs_compile_error**, ue2::Grey const&) ()
#3  0x00000000005977dc in hs_compile_multi ()
#4  0x0000000000588617 in regex_engine_compile (engine=0x9dacbc0) at marex_regex_engine.c:311

**Comment by xiangwang1** [comment]
We are not able to reproduce this issue given limited info. It'll be good if you can provide us more details including patterns, flags, mode, etc. You can also send us emails at xiang.w.wang@intel.com if your are concerned with privacy.

If possible, you can use our official tool hscollider (http://intel.github.io/hyperscan/dev-reference/tools.html) to double check if this is an internal error caused by Hyperscan itself.
