### ISSUE TITLE
hs_compile_lit_multi ASAN failure for empty patterns

### ISSUE THREAD

**Issue by danlark1** [intel/hyperscan#302]
Reproducible example

```cpp
#undef NDEBUG
#include <hs.h>
#include <cassert>
#include <string>

/*
Explanation: ASAN segfault.
Version: 5.4.0
==160188==The signal is caused by a READ memory access.
    #0 0xee2e4d in ue2::setupFDRFloodControl(std::vector<ue2::hwlmLiteral, std::allocator<ue2::hwlmLiteral> > const&, ue2::EngineDescription const&, ue2::Grey const&) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/fdr/flood_compile.cpp:111:16
    #1 0xee62cd in ue2::(anonymous namespace)::TeddyCompiler::build() /home/danilak/regexp_fuzzer/contrib/hyperscan/src/fdr/teddy_compile.cpp:570:23
    #2 0xee62cd in ue2::teddyBuildTable(ue2::HWLMProto const&, ue2::Grey const&) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/fdr/teddy_compile.cpp:658:15
    #3 0xec5257 in ue2::fdrBuildTableInternal(ue2::HWLMProto const&, ue2::Grey const&) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/fdr/fdr_compile.cpp:888:16
    #4 0xec5257 in ue2::fdrBuildTable(ue2::HWLMProto const&, ue2::Grey const&) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/fdr/fdr_compile.cpp:897:12
    #5 0xcb2eee in ue2::hwlmBuild(ue2::HWLMProto const&, ue2::CompileContext const&, unsigned long long) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/hwlm/hwlm_build.cpp:139:20
    #6 0xbb24b3 in ue2::buildHWLMMatcher(ue2::RoseBuildImpl const&, ue2::LitProto*) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/rose/rose_build_matchers.cpp:894:17
    #7 0xda5ef2 in ue2::RoseBuildImpl::buildFinalEngine(unsigned int) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/rose/rose_build_bytecode.cpp:3751:19
    #8 0xb6f1df in ue2::RoseBuildImpl::buildRose(unsigned int) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/rose/rose_build_compile.cpp:1796:12
    #9 0x4e2eaf in ue2::generateRoseEngine(ue2::NG&) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/compiler/compiler.cpp:436:26
    #10 0x4e2eaf in ue2::build(ue2::NG&, unsigned int*, unsigned char) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/compiler/compiler.cpp:509:17
    #11 0x4d6c2c in ue2::hs_compile_lit_multi_int(char const* const*, unsigned int const*, unsigned int const*, hs_expr_ext const* const*, unsigned long const*, unsigned int, unsigned int, hs_platform_info const*, hs_database**, hs_compile_error**, ue2::Grey const&) /home/danilak/regexp_fuzzer/contrib/hyperscan/src/hs.cpp:379:35
    #12 0x4d87cb in hs_compile_lit_multi /home/danilak/regexp_fuzzer/contrib/hyperscan/src/hs.cpp:484:12
    #13 0x4d0be9 in main /home/danilak/regexp_fuzzer/hyperscan_bugs/empty_string_segfault.cpp:40:22
    #14 0x7fa13de90d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #15 0x4243c9 in _start (/home/danilak/regexp_fuzzer/build_asan/hyperscan_bugs/empty_string_segfault+0x4243c9)
*/

int main() {
    hs_database_t *db = nullptr;
    hs_compile_error_t *compile_err = nullptr;
    // Haystack:
    const char* data = "\x00\x00\x00\x0a\x0a\x0a\x45\x45\x0a\x0a\x00\x00\x00";
    const size_t size = 13;
    // Patterns:
    const char *expr[] = {
        "",
        "\x73\x6f\x6d\x65\x20\x6e\x6f\x6e\x20\x65\x78\x69\x73\x74\x69\x6e\x67\x20\x73\x74\x72\x69\x6e\x67",
    };
    unsigned ids[] = {0, 1};
    size_t lens[] = {0, 24};
    unsigned flags[] = {HS_FLAG_CASELESS, HS_FLAG_SINGLEMATCH};
    hs_error_t err = hs_compile_lit_multi(expr, flags, ids, lens, sizeof(ids)/sizeof(*ids), HS_MODE_BLOCK, nullptr, &db, &compile_err);

    assert(HS_SUCCESS == err);
    assert(db != nullptr);

    hs_free_database(db);
}
```

**Comment by Nor7th** [comment]
Thanks for reporting the issue. Will fix it in next release.

**Comment by hongyang7** [comment]
Please refer to latest develop branch.
