### ISSUE TITLE
Assertion `!info.is_sherman(granddaddy)' failed.

### ISSUE THREAD

**Issue by danlark1** [intel/hyperscan#305]
Fails with assertion, if removing it, works fine

```cpp
#undef NDEBUG
#include <hs.h>
#include <cassert>

/*
Explanation: assertion failure.
Version: 5.4.0
hyperscan_string_fuzzer: ../contrib/hyperscan/src/nfa/mcclellancompile.cpp:1094: void ue2::find_better_daddy(ue2::(anonymous namespace)::dfa_info &, ue2::dstate_id_t, bool, bool, bool, const ue2::Grey &): Assertion `!info.is_sherman(granddaddy)' failed.
==2633272== ERROR: libFuzzer: deadly signal
    #9 0x119f6a0 in ue2::find_better_daddy(ue2::(anonymous namespace)::dfa_info&, unsigned short, bool, bool, bool, ue2::Grey const&) contrib/hyperscan/src/nfa/mcclellancompile.cpp:1094:13
    #10 0x119f6a0 in ue2::mcclellanCompile_i(ue2::raw_dfa&, ue2::accel_dfa_build_strat&, ue2::CompileContext const&, bool, std::__1::set<unsigned short, std::__1::less<unsigned short>, std::__1::allocator<unsigned short> >*) contrib/hyperscan/src/nfa/mcclellancompile.cpp:1496:17
    #11 0x11a26f9 in ue2::mcclellanCompile(ue2::raw_dfa&, ue2::CompileContext const&, ue2::ReportManager const&, bool, bool, std::__1::set<unsigned short, std::__1::less<unsigned short>, std::__1::allocator<unsigned short> >*) contrib/hyperscan/src/nfa/mcclellancompile.cpp:1526:12
    #12 0xbad424 in ue2::getDfa(ue2::raw_dfa&, ue2::CompileContext const&, ue2::ReportManager const&, bool, std::__1::set<unsigned short, std::__1::less<unsigned short>, std::__1::allocator<unsigned short> >&) contrib/hyperscan/src/smallwrite/smallwrite_build.cpp:804:15
    #13 0xb89b91 in ue2::prepEngine(ue2::raw_dfa&, unsigned int, ue2::CompileContext const&, ue2::ReportManager const&, bool, unsigned int*, unsigned int*) contrib/hyperscan/src/smallwrite/smallwrite_build.cpp:820:16
    #14 0xb89b91 in ue2::(anonymous namespace)::SmallWriteBuildImpl::build(unsigned int) contrib/hyperscan/src/smallwrite/smallwrite_build.cpp:923:16
    #15 0x1679193 in ue2::addSmallWriteEngine(ue2::RoseBuildImpl const&, ue2::RoseResources const&, ue2::bytecode_ptr<RoseEngine>) contrib/hyperscan/src/rose/rose_build_bytecode.cpp:3500:35
    #16 0x1679193 in ue2::RoseBuildImpl::buildFinalEngine(unsigned int) contrib/hyperscan/src/rose/rose_build_bytecode.cpp:3886:14
    #17 0x1322a85 in ue2::RoseBuildImpl::buildRose(unsigned int) contrib/hyperscan/src/rose/rose_build_compile.cpp:1796:12
    #18 0x7832f8 in ue2::generateRoseEngine(ue2::NG&) contrib/hyperscan/src/compiler/compiler.cpp:436:26
    #19 0x7832f8 in ue2::build(ue2::NG&, unsigned int*, unsigned char) contrib/hyperscan/src/compiler/compiler.cpp:509:17
    #20 0x77649a in ue2::hs_compile_lit_multi_int(char const* const*, unsigned int const*, unsigned int const*, hs_expr_ext const* const*, unsigned long const*, unsigned int, unsigned int, hs_platform_info const*, hs_database**, hs_compile_error**, ue2::Grey const&) contrib/hyperscan/src/hs.cpp:379:35
    #21 0x77821d in hs_compile_lit_multi contrib/hyperscan/src/hs.cpp:484:12
*/

int on_match(unsigned int id,
             unsigned long long from,
             unsigned long long to,
             unsigned int /* flags */,
             void * context) {
    return 0;
}

int main() {
    hs_database_t *db = nullptr;
    hs_compile_error_t *compile_err = nullptr;
    // Haystack:
    const char* data = "\x00\x00\xfd\xffv\x3f\x5e\x3b\x5c\x29  \xffVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\x3aVVVVVVVVVVVVVVVVVVVVVVVVVV\x00\x00\x00\x00 ";
    const size_t size = 79;
    // Patterns:
    const char *expr[] = {
        "n existi ",
        "\xfd\xffv\x3f\x5e\x3b\x5c\x29  \xffV",
        "VVVVVVVVVVVVVVVVVVVVVVVV",
        "VVVVVVVVVVVVVome none VV",
        "VVVVVV non eVVVVVVVVVVVV\x3aVVVVVVVV",
    };
    unsigned ids[] = {0, 1, 2, 3, 4};
    size_t lens[] = {9, 12, 24, 24, 33};
    unsigned flags[] = {0, HS_FLAG_CASELESS|HS_FLAG_SINGLEMATCH, HS_FLAG_SINGLEMATCH, HS_FLAG_CASELESS|HS_FLAG_SINGLEMATCH, HS_FLAG_CASELESS|HS_FLAG_SINGLEMATCH};
    hs_error_t err = hs_compile_lit_multi(expr, flags, ids, lens, sizeof(ids)/sizeof(*ids), HS_MODE_BLOCK, nullptr, &db, &compile_err);

    assert(HS_SUCCESS == err);
    assert(db != nullptr);
    hs_scratch_t *scratch = nullptr;
    err = hs_alloc_scratch(db, &scratch);
    assert(HS_SUCCESS == err);
    assert(scratch != nullptr);

    err = hs_scan(db, data, size, 0, scratch, on_match, nullptr);
    assert(HS_SUCCESS == err);

    hs_free_database(db);
    err = hs_free_scratch(scratch);
    assert(HS_SUCCESS == err);
}
```

**Comment by danlark1** [comment]
Pretty much the same when compiled with `hs_compile_multi`

```cpp
#undef NDEBUG
#include <hs.h>
#include <cassert>

/*
Explanation: assertion failure.
Version: 5.4.0
hyperscan_string_fuzzer: ../contrib/hyperscan/src/nfa/mcclellancompile.cpp:1094: void ue2::find_better_daddy(ue2::(anonymous namespace)::dfa_info &, ue2::dstate_id_t, bool, bool, bool, const ue2::Grey &): Assertion `!info.is_sherman(granddaddy)' failed.
==2633272== ERROR: libFuzzer: deadly signal
    #9 0x119f6a0 in ue2::find_better_daddy(ue2::(anonymous namespace)::dfa_info&, unsigned short, bool, bool, bool, ue2::Grey const&) contrib/hyperscan/src/nfa/mcclellancompile.cpp:1094:13
    #10 0x119f6a0 in ue2::mcclellanCompile_i(ue2::raw_dfa&, ue2::accel_dfa_build_strat&, ue2::CompileContext const&, bool, std::__1::set<unsigned short, std::__1::less<unsigned short>, std::__1::allocator<unsigned short> >*) contrib/hyperscan/src/nfa/mcclellancompile.cpp:1496:17
    #11 0x11a26f9 in ue2::mcclellanCompile(ue2::raw_dfa&, ue2::CompileContext const&, ue2::ReportManager const&, bool, bool, std::__1::set<unsigned short, std::__1::less<unsigned short>, std::__1::allocator<unsigned short> >*) contrib/hyperscan/src/nfa/mcclellancompile.cpp:1526:12
    #12 0xbad424 in ue2::getDfa(ue2::raw_dfa&, ue2::CompileContext const&, ue2::ReportManager const&, bool, std::__1::set<unsigned short, std::__1::less<unsigned short>, std::__1::allocator<unsigned short> >&) contrib/hyperscan/src/smallwrite/smallwrite_build.cpp:804:15
    #13 0xb89b91 in ue2::prepEngine(ue2::raw_dfa&, unsigned int, ue2::CompileContext const&, ue2::ReportManager const&, bool, unsigned int*, unsigned int*) contrib/hyperscan/src/smallwrite/smallwrite_build.cpp:820:16
    #14 0xb89b91 in ue2::(anonymous namespace)::SmallWriteBuildImpl::build(unsigned int) contrib/hyperscan/src/smallwrite/smallwrite_build.cpp:923:16
    #15 0x1679193 in ue2::addSmallWriteEngine(ue2::RoseBuildImpl const&, ue2::RoseResources const&, ue2::bytecode_ptr<RoseEngine>) contrib/hyperscan/src/rose/rose_build_bytecode.cpp:3500:35
    #16 0x1679193 in ue2::RoseBuildImpl::buildFinalEngine(unsigned int) contrib/hyperscan/src/rose/rose_build_bytecode.cpp:3886:14
    #17 0x1322a85 in ue2::RoseBuildImpl::buildRose(unsigned int) contrib/hyperscan/src/rose/rose_build_compile.cpp:1796:12
    #18 0x7832f8 in ue2::generateRoseEngine(ue2::NG&) contrib/hyperscan/src/compiler/compiler.cpp:436:26
    #19 0x7832f8 in ue2::build(ue2::NG&, unsigned int*, unsigned char) contrib/hyperscan/src/compiler/compiler.cpp:509:17
    #20 0x77649a in ue2::hs_compile_lit_multi_int(char const* const*, unsigned int const*, unsigned int const*, hs_expr_ext const* const*, unsigned long const*, unsigned int, unsigned int, hs_platform_info const*, hs_database**, hs_compile_error**, ue2::Grey const&) contrib/hyperscan/src/hs.cpp:379:35
    #21 0x77821d in hs_compile_multi
*/

int on_match(unsigned int id,
             unsigned long long from,
             unsigned long long to,
             unsigned int /* flags */,
             void * context) {
    return 0;
}

int main() {
    hs_database_t *db = nullptr;
    hs_compile_error_t *compile_err = nullptr;
    // Haystack:
    const char* data = "\x00\x00\xfd\xffv\x3f\x5e\x3b\x5c\x29  \xffVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\x3aVVVVVVVVVVVVVVVVVVVVVVVVVV\x00\x00\x00\x00 ";
    const size_t size = 79;
    // Patterns:
    const char *expr[] = {
        "n existi ",
        "ABv\\?\\^;\\\\\\)  BV",
        "VVVVVVVVVVVVVVVVVVVVVVVV",
        "VVVVVVVVVVVVVome none VV",
        "VVVVVV non eVVVVVVVVVVVV:VVVVVVVV",
    };
    unsigned ids[] = {0, 1, 2, 3, 4};
    unsigned flags[] = {0, HS_FLAG_CASELESS|HS_FLAG_SINGLEMATCH, HS_FLAG_SINGLEMATCH, HS_FLAG_CASELESS|HS_FLAG_SINGLEMATCH, HS_FLAG_CASELESS|HS_FLAG_SINGLEMATCH};
    hs_error_t err = hs_compile_multi(expr, flags, ids, sizeof(ids)/sizeof(*ids), HS_MODE_BLOCK, nullptr, &db, &compile_err);

    assert(HS_SUCCESS == err);
    assert(db != nullptr);
    hs_scratch_t *scratch = nullptr;
    err = hs_alloc_scratch(db, &scratch);
    assert(HS_SUCCESS == err);
    assert(scratch != nullptr);

    err = hs_scan(db, data, size, 0, scratch, on_match, nullptr);
    assert(HS_SUCCESS == err);

    hs_free_database(db);
    err = hs_free_scratch(scratch);
    assert(HS_SUCCESS == err);
}
```

**Comment by Nor7th** [comment]
Thanks for showing a corner case for an internal DFA optimization. Will fix that in next release.

**Comment by hongyang7** [comment]
Please refer to latest develop branch.
